### ISSUE TITLE
Agenda settings modal does not show default value

### ISSUE THREAD

**Issue by marianunez** [mattermost/mattermost-plugin-agenda#65] opened 2020-09-25 19:19 UTC
The Agenda Settings modal is not setting the default value when a channel has no meeting settings and shows the last meeting settings viewed previously. 

Steps: 
1. Go to a channel and set the Agenda hashtag (in the modal) to "myMeetingA{{Jan02}}".
2. Create a new channel. 
3. Open the Agenda settings modal. 

Observed:
Meeting hashtag shows "myMeetingA{{Jan02}}"

Expected: 
It should show a default value of the channel name.

**Comment by hanzei** [comment] 2020-10-12 09:18
@marianunez I can't reproduce this issue. On which server are you observing this? Which commit of Mattermost and the plugin is it running?

**Comment by icy-meteor** [comment] 2020-11-18 13:03
The agenda hashtag input box is producing some wierd behaviour. I want to discuss this with the right person to know the correct behaviour.

+1 to @marianunez , I am facing the same issue. But if you close the popup and open it again, it resets back to default value.
Would love to get this fixed, but need to discuss before that.

**Comment by icy-meteor** [comment] 2020-11-18 15:31
Looking into this.

**Comment by icy-meteor** [comment] 2020-11-19 05:54
Unable to reproduce either.

**Comment by hanzei** [comment] 2020-11-19 10:52
Given that two people are not able to reproduce this, I'm going to close it. @marianunez feel free to reopen if you are still encountering this issue.

**Closed by hanzei** 2020-11-19 10:52 UTC
Labels: Type/Bug
